// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservations.sql

package sqldb

import (
	"context"
	"time"
)

const createReservation = `-- name: CreateReservation :exec
INSERT INTO reservations (
    id, customer_id, room_number, check_in_date, nights, status,
    total_amount_cents, paid_amount_cents
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateReservationParams struct {
	ID               string    `json:"id"`
	CustomerID       string    `json:"customer_id"`
	RoomNumber       string    `json:"room_number"`
	CheckInDate      time.Time `json:"check_in_date"`
	Nights           int32     `json:"nights"`
	Status           string    `json:"status"`
	TotalAmountCents int32     `json:"total_amount_cents"`
	PaidAmountCents  int32     `json:"paid_amount_cents"`
}

func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) error {
	_, err := q.db.ExecContext(ctx, createReservation,
		arg.ID,
		arg.CustomerID,
		arg.RoomNumber,
		arg.CheckInDate,
		arg.Nights,
		arg.Status,
		arg.TotalAmountCents,
		arg.PaidAmountCents,
	)
	return err
}

const getReservation = `-- name: GetReservation :one
SELECT id, customer_id, room_number, check_in_date, nights, status, total_amount_cents, paid_amount_cents, created_at, updated_at FROM reservations
WHERE id = ? LIMIT 1
`

func (q *Queries) GetReservation(ctx context.Context, id string) (Reservation, error) {
	row := q.db.QueryRowContext(ctx, getReservation, id)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RoomNumber,
		&i.CheckInDate,
		&i.Nights,
		&i.Status,
		&i.TotalAmountCents,
		&i.PaidAmountCents,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationsByRoom = `-- name: GetReservationsByRoom :many
SELECT id, customer_id, room_number, check_in_date, nights, status, total_amount_cents, paid_amount_cents, created_at, updated_at FROM reservations
WHERE room_number = ?
ORDER BY check_in_date DESC
`

// Pour l'historique admin
func (q *Queries) GetReservationsByRoom(ctx context.Context, roomNumber string) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, getReservationsByRoom, roomNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RoomNumber,
			&i.CheckInDate,
			&i.Nights,
			&i.Status,
			&i.TotalAmountCents,
			&i.PaidAmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isRoomAvailable = `-- name: IsRoomAvailable :one
SELECT COUNT(*)
FROM reservations
WHERE room_number = ?
  AND status != 'CANCELLED' -- On ignore les réservations annulées
  AND (
    check_in_date < ?                  -- La résa existante commence avant la fin demandée
    AND DATE_ADD(check_in_date, INTERVAL nights DAY) > ? -- La résa existante finit après le début demandé
  )
`

type IsRoomAvailableParams struct {
	RoomNumber string    `json:"room_number"`
	EndDate    time.Time `json:"end_date"`
	StartDate  time.Time `json:"start_date"`
}

// Vérifie s'il y a un chevauchement de dates pour une chambre donnée.
// Retourne le nombre de conflits (0 = disponible, >0 = indisponible).
// Parametres : room_number, start_date (input), end_date (input = start + nights)
func (q *Queries) IsRoomAvailable(ctx context.Context, arg IsRoomAvailableParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isRoomAvailable, arg.RoomNumber, arg.EndDate, arg.StartDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listReservations = `-- name: ListReservations :many
SELECT id, customer_id, room_number, check_in_date, nights, status, total_amount_cents, paid_amount_cents, created_at, updated_at FROM reservations
ORDER BY check_in_date DESC
`

func (q *Queries) ListReservations(ctx context.Context) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, listReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RoomNumber,
			&i.CheckInDate,
			&i.Nights,
			&i.Status,
			&i.TotalAmountCents,
			&i.PaidAmountCents,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReservation = `-- name: UpdateReservation :exec
UPDATE reservations
SET status = ?, paid_amount_cents = ?
WHERE id = ?
`

type UpdateReservationParams struct {
	Status          string `json:"status"`
	PaidAmountCents int32  `json:"paid_amount_cents"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateReservation(ctx context.Context, arg UpdateReservationParams) error {
	_, err := q.db.ExecContext(ctx, updateReservation, arg.Status, arg.PaidAmountCents, arg.ID)
	return err
}
