// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqldb

import (
	"context"
)

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (room_number, type)
VALUES (?, ?)
`

type CreateRoomParams struct {
	RoomNumber string `json:"room_number"`
	Type       string `json:"type"`
}

// Utile pour le seeding ou l'admin
func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom, arg.RoomNumber, arg.Type)
	return err
}

const getRoom = `-- name: GetRoom :one
SELECT room_number, type FROM rooms
WHERE room_number = ? LIMIT 1
`

func (q *Queries) GetRoom(ctx context.Context, roomNumber string) (Room, error) {
	row := q.db.QueryRowContext(ctx, getRoom, roomNumber)
	var i Room
	err := row.Scan(&i.RoomNumber, &i.Type)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT room_number, type FROM rooms
ORDER BY room_number
`

func (q *Queries) ListRooms(ctx context.Context) ([]Room, error) {
	rows, err := q.db.QueryContext(ctx, listRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(&i.RoomNumber, &i.Type); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
