// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package sqldb

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO customers (id, email, phone, full_name, wallet_sold)
VALUES (?, ?, ?, ?, ?)
`

type CreateCustomerParams struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	FullName   string `json:"full_name"`
	WalletSold string `json:"wallet_sold"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.ExecContext(ctx, createCustomer,
		arg.ID,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.WalletSold,
	)
	return err
}

const deleteCustomer = `-- name: DeleteCustomer :execrows
DELETE FROM customers
WHERE id = ?
`

func (q *Queries) DeleteCustomer(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCustomer, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, email, phone, full_name, wallet_sold
FROM customers
WHERE email = ? LIMIT 1
`

func (q *Queries) GetCustomerByEmail(ctx context.Context, email string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByEmail, email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.WalletSold,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, email, phone, full_name, wallet_sold
FROM customers
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id string) (Customer, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.FullName,
		&i.WalletSold,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, email, phone, full_name, wallet_sold
FROM customers
ORDER BY full_name ASC
`

func (q *Queries) ListCustomers(ctx context.Context) ([]Customer, error) {
	rows, err := q.db.QueryContext(ctx, listCustomers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.FullName,
			&i.WalletSold,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :execrows
UPDATE customers
SET email = ?, phone = ?, full_name = ?, wallet_sold = ?
WHERE id = ?
`

type UpdateCustomerParams struct {
	Email      string `json:"email"`
	Phone      string `json:"phone"`
	FullName   string `json:"full_name"`
	WalletSold string `json:"wallet_sold"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateCustomer,
		arg.Email,
		arg.Phone,
		arg.FullName,
		arg.WalletSold,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
